### PR TITLE
Allow `Buffer` types, `Reader`, and `Writer` to accept `?Sized` types

### PR DESCRIPTION
**Pull request by wackbyte**
Allows slices to be used.

### CODE REVIEW

**Review by teoxoy — APPROVED** [review]
Thanks! Will release a new minor version.

**Comment by teoxoy** [comment]
Actually, I bumped a few dependencies between the last version and now, so I can't release a minor version.

Do you mind waiting a bit longer for the release? You can still use encase as a git dep.

**Comment by wackbyte** [comment]
That's alright!

**Comment by teoxoy** [comment]
v0.7 has been released!

**Pull request merged**
