### PR TITLE
Update `glam` to 0.28

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
An alternative might be to use a version constraint like `version = ">=0.25, <=0.28"` but that might be tricker to handle in CI for testing.

**Comment by mnmaita** [comment]
> An alternative might be to use a version constraint like `version = ">=0.25, <=0.28"` but that might be tricker to handle in CI for testing.

Thinking out loud: maybe this could be done via a job matrix, then using `cargo update glam --precise x.x.x`? A problem I see with this approach is how to cleanly get the supported version list.

**Comment by teoxoy** [comment]
> An alternative might be to use a version constraint like `version = ">=0.25, <=0.28"` but that might be tricker to handle in CI for testing.

That would be ideal but probably not necessary as I think that most users of this crate update deps as soon as possible.
Let's keep things simple unless there is a request from someone.

**Review by teoxoy — APPROVED** [review]
Thanks!

**Pull request merged**
