### PR TITLE
upgrade nalgebra to version 0.32

### PR DESCRIPTION
**Pull request by JMLX42**
Related to https://github.com/teoxoy/encase/issues/22

- [x] Upgrade nalgebra
- [x] Fix 24 deprecation warnings
- [x] Upgrade MSRV to 1.61 (cf https://github.com/teoxoy/encase/pull/23#issuecomment-1419726075)

### CODE REVIEW

**Comment by JMLX42** [comment]
@teoxoy builds fine with `rustc` 1.66.1. Should I upgrade `rust-version` accordingly or try to bisect to keep it as low as possible?

**Comment by teoxoy** [comment]
I think we can bump our MSRV to 1.61 (https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html).

**Comment by JMLX42** [comment]
> I think we can bump our MSRV to 1.61 (https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html).

@teoxoy Done in ca84bb7078f375b22a30d06e6d073359bccadf43

**Comment by JMLX42** [comment]
@teoxoy https://github.com/teoxoy/encase/actions/runs/4107766204/jobs/7087641930 is failing ❌ but AFAIK it's not related to this PR. Everything else is apparently good to go.

**Comment by teoxoy** [comment]
Looks good, thank you for the PR!

I fixed the clippy warnings on `main`.

**Pull request merged**
