### PR TITLE
Update `glam` to 0.29

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
PRs #81 and #82 should fix the CI issues.

**Comment by waywardmonkeys** [comment]
@teoxoy Just checking in on this and the other pending PRs ... If there's anything that I need to do, just let me know!

**Comment by teoxoy** [comment]
Sorry for the wait and thanks for all the PRs!

**Review by teoxoy — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
> Sorry for the wait and thanks for all the PRs!

Thanks for getting it all in!

**Comment by teoxoy** [comment]
encase v0.10 is up on crates.io

**Pull request merged**
